random_state: 2025

folders:
  data: artifacts/data
  models: artifacts/models
  eval: artifacts/evaluation

data:
  url: https://huggingface.co/datasets/SetFit/bbc-news/resolve/main/bbc-text.csv
  filename: bbc-text.csv
  test_size: 0.3

feature_eng:
  sentence_transformers:
    model_name: 'all-MiniLM-L6-v2'
    # batch_size: 32
    device: 'cpu'

model:
  logistic_regression:
    max_iter: 1000